var main = function() {
$('.a1').click(function(){
$('.one').toggle().siblings('.toggle').hide();
});
$('.a2').click(function(){
$('.two').toggle().siblings('.toggle').hide();
});
$('.a3').click(function(){
$('.three').toggle().siblings('.toggle').hide();
});
$('.a4').click(function(){
$('.four').toggle().siblings('.toggle').hide();
});
$('.a5').click(function(){
$('.five').toggle().siblings('.toggle').hide();
});
$('.a6').click(function(){
$('.six').toggle().siblings('.toggle').hide();
});
$('.a7').click(function(){
$('.seven').toggle().siblings('.toggle').hide();
});
$('.a8').click(function(){
$('.eight').toggle().siblings('.toggle').hide();
});
$('.a9').click(function(){
$('.nine').toggle().siblings('.toggle').hide();
});
$('.a10').click(function(){
$('.ten').toggle().siblings('.toggle').hide();
});

};
$(document).ready(main);